### ISSUE TITLE
Object reference error

### ISSUE THREAD

**Issue by sahilpma** [MaksymHernets/AutoTranslateForUnityLocalization#11]
This used work fine, but after updating, it is giving this error

Object reference not set to an instance of an object
UnityEngine.Debug:LogError (object)
GoodTime.HernetsMaksym.AutoTranslate.Windows.AutoTranslate_EditorWindow:ButtonTranslate_Click () (at Library/PackageCache/com.maksymhernets.autotranslateforunitylocalization@d0eb7b234d/AutoTranslate/Editor/AutoTranslate_EditorWindow.cs:144)
GoodTime.HernetsMaksym.AutoTranslate.Windows.AutoTranslate_EditorWindow:OnGUI () (at Library/PackageCache/com.maksymhernets.autotranslateforunitylocalization@d0eb7b234d/AutoTranslate/Editor/AutoTranslate_EditorWindow.cs:92)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

![image](https://user-images.githubusercontent.com/38884892/194315799-708e6db3-c887-4aaf-a92f-63e2fc667656.png)

**Comment by MaksymHernets** [comment]
Thanks for the report. I have not been able to reproduce this issue. Can you please determine on which table the error occurs, and then take a screenshot with the contents of the table. Maybe you are using special characters, I don't know.

**Comment by MaksymHernets** [comment]
If the table is large, try loading this table via a comment

**Comment by sahilpma** [comment]
sorry... the issue is on my side... Actually there was one table with no keys... so I deleted and it worked like charm...
