### ISSUE TITLE
References to UnityEditor

### ISSUE THREAD

**Issue by merksk8** [MaksymHernets/AutoTranslateForUnityLocalization#14]
Hello,

I'm trying to use the asset, but when I try to build it doesn't work. The reason is because there's a lot of references to UnityEditor in scripts that are not in Editor folder, or encapsulated with #if UNITY_EDITOR.

Am i doing something wrong? Should i put the folder in any specific place to prevent this error? 

I'm using latest version of the asset and Unity 2021.3.27f

PD: I would fix it, but there's a lot of references everywhere. Tried easy fixes as removing the files, moving them all to Editor folder, but couldn't get it to work.

Thank you!

**Comment by MaksymHernets** [comment]
Hi, thanks for the feedback. But I don't have time now to check what the
problem is during project compilation. According to the idea, you can make
a translation using my tool, then remove it from the project, then there
should be no conflicts. To import my tool, use the package manager and link
https://github.com/MaksymHernets/AutoTranslateForUnityLocalization.git?path=/Assets.
Then in the windows tab you can find my tool called Auto Localization

пт, 16 июн. 2023 г. в 11:42, merk_cat ***@***.***>:

**Comment by merksk8** [comment]
Yeah that's what I'm doing, works fine that way.

If i have time to fix it I'll send a pull request.

Thanks anyway!

**Comment by MaksymHernets** [comment]
I will be grateful. According to the idea, you just need to remove the
assembler definition from the editor folder, the unit itself will ignore
this folder when compiling, because it is named editor

пт, 16 июн. 2023 г. в 14:19, merk_cat ***@***.***>:

**Comment by MaksymHernets** [comment]
@merksk8  Thank for fixed bug
